# docker-compose.yml
version: '3'
services:
  database:
    image: 'postgres' # use latest official postgres version
    # container_name: own_db
    env_file:
      - database.env # configure postgres
    ports:
      - '3003:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
